name: build_qt6.5_win_msvc2022_amd64

on: workflow_dispatch
#on: [push, pull_request]

env:
  QT_VERSION: 6.5.6
  QT_VERSION2: 6.5
  FILE_NAME: release_win_msvc2022_amd64

jobs:
  windows_msvc_release:
    runs-on: windows-latest

    steps:
    # 检出本仓库
    - name: Checkout repository
      uses: actions/checkout@v4

    # 安装python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        architecture: 'x64'

    # 安装msvc
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    # 安装vsdevenv
    - name: Setup vsdevenv
      uses: seanmiddleditch/gha-setup-vsdevenv@master

    # 构建Qt
    - name: Build Qt
      run: |
        #ls     #Directory: D:\a\qt-builder\qt-builder(即仓库目录)
        #D:\a\qt-builder                                上级目录，这里当做根目录
        #D:\a\qt-builder\Qt                             Qt目录
        #D:\a\qt-builder\Qt\${{env.QT_VERSION}}         Qt目录源代码和build文件夹存放目录
        #D:\a\qt-builder\Qt\${{env.QT_VERSION}}-install  Qt安装目录
        
        # 创建文件夹
        cd ..  #Directory: D:\a\qt-builder
        mkdir -p Qt

        # 创建文件夹
        cd Qt   #Directory: D:\a\qt-builder\Qt
        mkdir -p ${{env.QT_VERSION}}
        mkdir -p ${{env.QT_VERSION}}-install

        # 下载源代码并解压,源代码目录D:\a\qt-builder\Qt\${{env.QT_VERSION}}\XXX
        curl -L -o qt-everywhere-src.zip https://download.qt.io/official_releases/qt/${{env.QT_VERSION2}}/${{env.QT_VERSION}}/src/single/qt-everywhere-opensource-src-${{env.QT_VERSION}}.zip
        unzip -q qt-everywhere-src.zip -d ./${{env.QT_VERSION}}

        # 调用编译脚本
        cmd.exe /c "call `"D:\a\qt-builder\qt-builder\build_qt6.5_win_msvc2022_amd64.cmd`""

    # 打包
    - name: Package binaries
      run: |
        #ls     #Directory: D:\a\qt-builder\qt-builder(即仓库目录)
        7z a Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z ../Qt/${{env.QT_VERSION}}-install -mx=9

    # 上传
    - uses: actions/upload-artifact@v4
      with:
        name: Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}
        path: Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z
