name: build_qt6.5_android_ndk27_armv8

on: workflow_dispatch

env:
  QT_VERSION: 6.5.6
  QT_VERSION2: 6.5
  ANDROID_NDK_VERSION: 27.2.12479018
  ANDROID_JDK_VERSION: 17
  ANDROID_API: 35
  ANDROID_BUILD_TOOLS_VERSION: 35.0.0
  ARCH: arm64-v8a
  FILE_NAME: release_android_ndk27_armv8

jobs:
  android_armv8_release:
    runs-on: ubuntu-22.04

    steps:
    # 检出本仓库 /home/runner/work/qt-builder/qt-builder (仓库目录)
    - name: Checkout repository
      uses: actions/checkout@v4

    # 修复 sources.list
    - name: Fix Ubuntu sources list
      run: |
        sudo cat << EOF | sudo tee /etc/apt/sources.list
        deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ jammy main restricted
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy main restricted

        deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy-updates main restricted

        deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ jammy universe
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy universe

        deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ jammy-updates universe
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy-updates universe

        deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ jammy multiverse
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy multiverse

        deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ jammy-updates multiverse
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy-updates multiverse

        deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy-backports main restricted universe multiverse

        deb [arch=amd64] http://security.ubuntu.com/ubuntu/ jammy-security main restricted
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy-security main restricted

        deb [arch=amd64] http://security.ubuntu.com/ubuntu/ jammy-security universe
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy-security universe

        deb [arch=amd64] http://security.ubuntu.com/ubuntu/ jammy-security multiverse
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ jammy-security multiverse
        EOF

    # 安装更新 安装依赖
    - name: Install updates
      run: |
        cd /home/runner/work/qt-builder
        export DEBIAN_FRONTEND=noninteractive
        # sudo dpkg --add-architecture arm64
        sudo apt-get -y update
        sudo apt-get -y upgrade
        sudo apt-get -y install build-essential git perl python3 python3-pip ninja-build cmake libgl1-mesa-dev libglu1-mesa-dev \
        llvm-15 llvm-15-dev clang-15 libclang-15-dev

    # 安装android依赖
    - name: Install android dependencies
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-${{env.ANDROID_JDK_VERSION}}-openjdk-amd64
        sudo apt-get install -y openjdk-${{env.ANDROID_JDK_VERSION}}-jdk sdkmanager
        sudo sdkmanager "platforms;android-${{env.ANDROID_API}}" "platform-tools" "build-tools;${{env.ANDROID_BUILD_TOOLS_VERSION}}"
        export ANDROID_SDK_ROOT=/opt/android-sdk
        sudo sdkmanager "ndk;${{env.ANDROID_NDK_VERSION}}"
        export ANDROID_NDK_ROOT=/opt/android-sdk/ndk/${{env.ANDROID_NDK_VERSION}}

    # 下载Qt源代码
    - name: Download Qt source
      run: |
        sudo curl -L -o qt-everywhere-src.tar.xz https://download.qt.io/official_releases/qt/${{env.QT_VERSION2}}/${{env.QT_VERSION}}/src/single/qt-everywhere-opensource-src-${{env.QT_VERSION}}.tar.xz
        sudo tar xvfp qt-everywhere-src.tar.xz

    # 编译Qt host tools
    - name: Build Qt host tools
      run: |
        sudo mkdir build-host
        cd build-host
        sudo ../qt-everywhere-src-${{env.QT_VERSION}}/configure -developer-build -nomake tests -nomake examples
        sudo cmake --build . --target host_tools

    # 编译Qt android
    - name: Build Qt android
      run: |
        sudo mkdir build
        cd build
